export const LOGIN_DETAILS = "LOGIN_DETAILS";
export const LOGIN_DETAILS_SUCCESS = "LOGIN_DETAILS_SUCCESS";
export const LOGIN_DETAILS_FAILED = "LOGIN_DETAILS_FAILED";

export const LOG_OUT = "LOG_OUT";
