export const FETCH_SALARY_DETAILS = "FETCH_SALARY_DETAILS";
export const FETCH_SALARY_DETAILS_SUCCESS = "FETCH_SALARY_DETAILS_SUCCESS";
export const FETCH_SALARY_DETAILS_FAILED = "FETCH_SALARY_DETAILS_FAILED";

export const SUBMIT_SALARY_DETAILS = "SUBMIT_SALARY_DETAILS";
export const SUBMIT_SALARY_DETAILS_SUCCESS = "SUBMIT_SALARY_DETAILS_SUCCESS";
export const SUBMIT_SALARY_DETAILS_FAILED = "SUBMIT_SALARY_DETAILS_FAILED";

export const NOTIFY_USER_EMAIL_DETAILS = "NOTIFY_USER_EMAIL_DETAILS";
export const NOTIFY_USER_EMAIL_DETAILS_SUCCESS = "_SUCCESS";
export const NOTIFY_USER_EMAIL_DETAILS_FAILED =
  "NOTIFY_USER_EMAIL_DETAILS_FAILED";

export const CLEAR_SUBMIT_SALARY = "CLEAR_SUBMIT_SALARY";

export const UPDATE_MASTER_SALARY_TABLE_DETAILS =
  "UPDATE_MASTER_SALARY_TABLE_DETAILS";
export const UPDATE_MASTER_SALARY_TABLE_DETAILS_SUCCESS =
  "UPDATE_MASTER_SALARY_TABLE_DETAILS_SUCCESS";
export const UPDATE_MASTER_SALARY_TABLE_DETAILS_FAILED =
  "UPDATE_MASTER_SALARY_TABLE_DETAILS_FAILED";

export const DELETE_MASTER_SALARY_TABLE_DETAILS =
  "DELETE_MASTER_SALARY_TABLE_DETAILS";
export const DELETE_MASTER_SALARY_TABLE_DETAILS_SUCCESS =
  "DELETE_MASTER_SALARY_TABLE_DETAILS_SUCCESS";
export const DELETE_MASTER_SALARY_TABLE_DETAILS_FAILED =
  "DELETE_MASTER_SALARY_TABLE_DETAILS_FAILED";
